# Don't edit this file!!

UNITY=/Applications/Unity/Unity.app/Contents/MacOS/Unity
TARGET_FILES= Assets/Plugins/KeyboardInputDetector
OUT_PACKAGE=../KeyboardInputDetector.unitypackage
PROJ_PATH= ./LibraryUser

pkg:
	$(UNITY) -exportPackage $(TARGET_FILES) $(OUT_PACKAGE) -projectPath $(PROJ_PATH) -batchmode -nographics -quit
